[google_service_account]
type = "service_account"
project_id = "red-bruin-455017-f8"
private_key_id = "009e702d1a8b2dab9b35b2fd6507ecd334421f03"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDJefhZLxSegaMg
p0Jdv7AZMypdycvRTEJx0uvH/cRkRnDihHYvE9h2Ulcd8p4p/hDtouxV9wjnwMJ8
1oY1m8QJU+GLq5PAVpsxjd1jwa8edi5QRB8WTItDxiumeuSos0/FlWcS7r/iyqwV
RjgYyGElZcio155+QxRiBRYjBZ52Qj7JJVLVbyfttmVd3GEbI2tTWexTIMBPLg7V
R0BYYCKHjS0azAPsnA1XoCOWM7EQ2NkzyqRmmnVo+KJ0Cdz49oklFsswd7yBvWDD
rE2IhEMbKyt2Y9na7I05Ef+Hmb40L1Sk9knxTg1UUQxnTRNanjOvAvhkuKCoEhu6
3eJ+uWEjAgMBAAECggEADuRBAvaD46NZV1SFh0Bf17z8aKo9sl6cmqUoYEPVfEPo
nBWGVrx0x2oWnlQMdLYesjHUnhYARoDs3yVMDjJRLw9QIG6yIQlFt0fxESqDsxCx
I6WlVpSZxoyjNU7oD8ARKV19nNygujaYuYnTI6HL7GO1jSVCxbpXi1cs57HGoJ7r
Pqc2SNTIKH6CFj5CWJ/kRbgC9OJikPW8VRJ3r1IiY4ntODkJPI0jHw8CkmHWlTXr
c9UpXc5nbRC0pnryIrylaHbZdaeYJkCN+LFlCn+34bdXDdoCWlvCWpcSr5liDFHv
3+Ksd2OlgHAnDcM1THBYWGPbJGaxTyT0vTTU4cgBwQKBgQDvWGnN3POXPlYlsJXI
ulIKWFXpcFS33ycyXkXo8MHlP/lNmZEMhYvaPawKBYgZIGBrd9sVHV2pRuAv0DWx
LrWNFhLByunBhK4GYVoZ3SvBCedDKqY+z1zqtuZH4LrhTGilrCZskvdTd6hb4LCE
tUhu4Wx6u6Vauez7sKNX3ATwywKBgQDXfvpBHEIDZ8iKrry7856YtC7jjVKCcowu
+N2TWLlrRoEEzueZdYYs9edUeIytw2qnJB8PckKmvoVv71F+/a/1qHmurm4s/d5M
J5Yt956QyhDrnX6ZVaY3aw2hvKQCBV9M/91gHQL3X6MCPBSt83bqmqGCFg70ciXD
9/c1F/t+CQKBgBwUqm0ttCKVfLP1UM15FrECBipaNIZSFx4ws1EOFiGYbN5u2va2
IF9dhvayCXKxOr7BFCIZDOkUWK8jZXlBOqmv4kl8TgqXT3eOKm0IZt7CE7Dsqw6J
c6RSCxh5xFM0jL6LQQLSB1RyoH0PEoavYi0oI3sO0uqfD6/D3JYtSSMbAoGAGwP4
K6F3RSYFph0x2/42q74rAqv85A2oNVtNq+M7m49DLW8i6cIqCAjr71MNj9sny7xj
iHQyluTbpaTC+sCjBpEQcC298jYBYFq2IR0h69TpOiCMdnyeUeRB2Tzk8rvprqWF
Az+f15NNxEHz9brH9bFc/gn15f9JbL/xZd6T0MECgYBW6xEXDfHf/x5Sd7LwsIFz
6VKnUyxhx3xLwVE5lEy2qYveluJb/F2F1iREkSj7s77i4M6SXxDrXgl/UuI+k+Ax
D7Ji9arYuzNZTVStDXlrOLRwIWqlWrLYRTdqpH7hxd8+6ziSHflHT+Bw9fmtVghT
2P+3RH1qJMCnNc8ae13w0w==
-----END PRIVATE KEY-----"""
client_email = "validador-compras@red-bruin-455017-f8.iam.gserviceaccount.com"
client_id = "110064839267036830759"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/validador-compras%40red-bruin-455017-f8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[email]
sender = "matheus.neves@moonventures.com.br"
password = "qoxvmxwniwaluhob"
smtp_server = "smtp.gmail.com"
smtp_port = 587
